### ISSUE TITLE
License available

### ISSUE THREAD

**Issue by blankdots** [lajonss/pyeureka#4]
Hei,
I have been trying out this module, and it simply works and I like that.

However I have more of a question rather than a issue regarding the (re)use of the library regarding the license, as I want to use (build on) your code in my project and I do not see a license attached to the github repository nor an official python module available.

Could you attach a license to the repo or have a pypi module available?

Thank you!

**Comment by lajonss** [comment]
Sure, I've attached a license.

**Comment by lajonss** [comment]
I'd love to publish it as a pypi module, but unfortunately I can't register on the Warehouse site (captcha doesn't let me to do so). Maybe I'll do it some other time.
I've attached the license though.

**Comment by blankdots** [comment]
Ok, thanks!
Closing the issue :)

**Comment by lajonss** [comment]
I've uploaded the module to pypi.
